var elForm = document.getElementById('theForm');
var fixMsg = document.getElementById('theErrors');
var msg;
var letters = /^[A-Za-z]+$/;

function validateMe() {
    //Reset errors to blank  
    msg='';
        
    //First name check
    firstName = document.getElementById('firstname').value;
    if (firstName===null || firstName==="" || firstName.length > 20 || !firstName.match(letters)){
      msg += '<p>The first name is required and cannot be greater than 20 characters</p>';
    }

    //Last name check
    lastName = document.getElementById('lastname').value;
    if (lastName===null || lastName==="" || lastName.length > 50 || !lastName.match(letters)){
      msg += '<p>The last name is required and cannot be greater than 50 characters.</p>';
    }

    //email check
    var userEmail = document.getElementById("email").value;
    var atpos = userEmail.indexOf("@");
    var dotpos = userEmail.lastIndexOf(".");
    if (atpos< 1 || dotpos<atpos+2 || dotpos+2>=userEmail.length) {
      msg += "<p>Invalid email</p>";
    }

    //address check
    var addy = document.getElementById('address').value;
    if (addy===null || addy==="") {
      msg += '<p> Error: address</p>';
    }

    //district check
    var city = document.getElementById('district').value;
    if (district===null || district==="") {
      msg += '<p> Error: city</p>';
    }

  //Add the errors messages into div
    fixMsg.innerHTML = msg;
  //If an error message is present, prevent submission.
    if (msg !== '') {event.preventDefault();}
  
}
/*this code runs validateMe function before the submit button can do it's thing.  It's listening for the even "submit" and first runs the function.  If any errors are generated by the validateMe function, it stops the "submit" from happening.*/
elForm.addEventListener('submit', validateMe, false);