var elForm = document.getElementById('theForm');
var fixMsg = document.getElementById('theErrors');
var msg;

function validateMe() {
    msg='';
    //Reset errors to blank
    //First name check
    firstName = document.getElementById('firstname').value;
    if (firstName===null || firstName==="" || firstName.length > 20){
      msg += '<p>The first name is required and cannot be greater than 20 characters</p>';
    }

    //Last name check
    lastName = document.getElementById('lastname').value;
    if (lastName===null || lastName==="" || lastName.length > 50){
      msg += '<p>The last name is required and cannot be greater than 50 characters.</p>';
    }

    //email check
    var userEmail = document.getElementById("email").value;
    var atpos = userEmail.indexOf("@");
    var dotpos = userEmail.lastIndexOf(".");
    if (atpos< 1 || dotpos<atpos+2 || dotpos+2>=userEmail.length) {
      msg += "<p>Invalid email</p>";
    }
    
    //Phone Number Check
    var phone = document.getElementById("phone").value;
    if (isNaN(phone) || phone.length >15 || phone===null || phone==="") {
      msg += "<p>Invalid phone number </p>";
    }

    //usesrname name check
    var username = document.getElementById('username').value;
    if (username===null || username==="" || username.length > 12){
      msg += '<p>A Username is required and cannot be greater than 12 characters</p>';
    }

    //password check
    var passwyrd = document.getElementById('passwyrd').value;
    if (passwyrd===null || passwyrd==="" || passwyrd.length > 7){
      msg += '<p>Trust me, you will want a password, you can do it, 7 characters or less.  I believe in you</p>'
    }

    //address check
    var addy = document.getElementById('address').value;
    if (addy===null || addy==="") {
      msg += '<p> We need your address to continue </p>';
    }

    //city check
    var city = document.getElementById('city').value;
    if (city===null || city==="") {
      msg += '<p> It is not a full address without a city, friend.</p>';
    }

    //Country and Zip Check? Maybe?
    var country = document.getElementById("countries").value;
    var zipcode = document.getElementById("zipcode").value;
    if (country==="United States") {
    if (zipcode==="" || isNaN(zipcode) || zipcode.length>5) {
        msg += '<p>Check zip</p>';
    }
  }
  //Add the errors messages into div
  fixMsg.innerHTML = msg;
  //If an error message is present, prevent submission.
  event.preventDefault();

//i'm clearly an idiot groping for something here...
//  if (msg=""){
//    window.open('https://generalchickencat.github.io/PROG-109/Module08/Artifact04/ThankYou.html','_blank')
//  }

}

/*this code runs validateMe function before the submit button can do it's thing.  It's listening for the even "submit" and first runs the function.  If any errors are generated by the validateMe function, it stops the "submit" from happening.*/
elForm.addEventListener('submit', validateMe, false);

